language: python
python:
- "2.7"

os:
- linux

# Default environment is Ubuntu 12.04.5 LTS "precise"
# which is pretty old.
# "trusty" is Ubuntu 14.04.5 LTS
dist: trusty

# use the newer container-based infrastructure
#sudo: false
sudo: required

# python versions to test against...
# - osx

compiler:
  - g++

cache:
  directories:
  - $HOME/astrometry.net
  - $HOME/tractor
  - $HOME/dust
  - $HOME/tmv-0.73
  - $HOME/GalSim

# Additonal apt-get installs
addons:
  apt:
    packages:
    - graphviz
    - texlive-latex-extra
    - dvipng
    - libnetpbm10
    - libnetpbm10-dev
    - netpbm
    - wcslib-dev
    - libcfitsio3
    - libcfitsio3-dev
    - swig
    - gsl-bin
    - libgsl0-dev
    - libboost-all-dev
    - gfortran
    - liblapack-dev
    - libfftw3-dev
    - scons
    - curl

#before install:
#  - sudo apt-get install -y graphviz
#  - sudo apt-get install -y texlive-latex-extra
#  - sudo apt-get install -y dvipng
#  - sudo apt-get install -y libnetpbm10
#  - sudo apt-get install -y libnetpbm10-dev
#  - sudo apt-get install -y netpbm
#  - sudo apt-get install -y wcslib-dev
#  - sudo apt-get install -y libcfitsio3
#  - sudo apt-get install -y libcfitsio3-dev
#  - sudo apt-get install -y swig
#  - sudo apt-get install -y gsl-bin
#  - sudo apt-get install -y libgsl0-dev

install:
  - export WCSLIB_INC="-I/usr/include/wcslib-4.20"
  - export WCSLIB_LIB="-lwcs"
  #- pip install -r requirements.txt
  - which python
  - which pip
  - pip install Sphinx==1.5.4
  - pip install numpy
  - pip install scipy
  - pip install matplotlib 
  - pip install numpydoc
  - pip install astropy
  - pip install photutils
  - pip install cython
  - pip install h5py
  - pip install pandas
  - pip install psycopg2
  - pip install scikit-image
  - pip install scikit-learn
  - pip install nose future pyyaml
  - pip install coveralls
  - pip install --no-deps --upgrade git+https://github.com/esheldon/fitsio.git#egg=fitsio
  #- pip install -v --no-deps --upgrade git+https://github.com/dstndstn/tractor.git

before_script:
    - export MYCODE=$HOME/mycode
    - if [ ! -d "$HOME/astrometry.net" ]; then (cd $HOME && curl -SL https://github.com/dstndstn/astrometry.net/releases/download/0.72/astrometry.net-0.72.tar.gz -o astrometry.net.tar.gz && tar -xzf astrometry.net.tar.gz && mv astrometry.net-0.72 astrometry.net); fi
    - (cd $HOME/astrometry.net && make install INSTALL_DIR=$MYCODE/astrometry)
    - export PYTHONPATH=$MYCODE/astrometry/lib/python:$PYTHONPATH
    - export PATH=$MYCODE/astrometry/lib/python/astrometry/util:$PATH
    - export PATH=$MYCODE/astrometry/lib/python/astrometry/blind:$PATH
    - if [ ! -d "$HOME/tractor" ]; then (cd $HOME && curl -SL https://github.com/dstndstn/tractor/archive/dr5.2.tar.gz -o tractor.tar.gz && tar -xzf tractor.tar.gz && mv tractor-dr5.2 tractor); fi
    - cd $HOME/tractor 
    - make 
    - python setup.py install --prefix=$MYCODE/tractor
    - export PYTHONPATH=$MYCODE/tractor/lib/python2.7/site-packages:$PYTHONPATH
    - mkdir -p $HOME/dust/maps
    - (cd $HOME/dust/maps && wget -c http://portal.nersc.gov/project/cosmo/temp/dstn/travis-ci/maps/SFD_dust_4096_ngp.fits)
    - (cd $HOME/dust/maps && wget -c http://portal.nersc.gov/project/cosmo/temp/dstn/travis-ci/maps/SFD_dust_4096_sgp.fits)
    - export DUST_DIR=$HOME/dust
    - cd $HOME
    - if ! test -d tmv-0.73 || ! test -f tmv-0.73/Sconstruct; then wget https://github.com/rmjarvis/tmv/archive/v0.73.tar.gz && tar -xf v0.73.tar.gz ; else echo Using cached TMV; fi
    - cd $HOME/tmv-0.73 
    - sudo scons DEBUG=True FLAGS="-O0"
    - sudo scons install 
    - if [ ! -d "$HOME/GalSim" ]; then (cd $HOME && wget https://github.com/GalSim-developers/GalSim/archive/v1.4.2.tar.gz -O GalSim.tar.gz && tar -xzf GalSim.tar.gz && mv GalSim-1.4.2 GalSim); fi
    - ls $HOME
    - cd $HOME/GalSim
    - sudo scons PYTHON=/home/travis/virtualenv/python2.7.13/bin/python 
    - sudo scons install

script: 
  - python -c "import galsim; print(galsim.__file__)"
  - python -c "import tractor; print(tractor.__file__)"
  - python -c "import astrometry; print(astrometry.__file__)"
  - echo foo
  - cd py
  - coverage run obiwan/test/print_test.py test
#  - export PYTHONPATH=${PYTHONPATH}:$(pwd)/py:$HOME/astrometry.net
#  - cd py
#  - coverage run obiwan/test/obiwan_test_suite.py test

after_success: echo yay
#- (cd py && coveralls debug)
#    - (cd py && coveralls)




